name: build

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - ".editorconfig"
      - ".gitattributes"
      - ".gitignore"
      - "README.md"

env:
  DOTNET_VERSION: 7.x
  SOLUTION: TodoApp.sln
  BUILD_CONFIGURATON: Release

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET ${{env.DOTNET_VERSION}}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}

      - name: Restore NuGet packages
        run: dotnet restore ${{env.SOLUTION}}

      - name: Build solution
        run: dotnet build ${{env.SOLUTION}} --configuration ${{env.BUILD_CONFIGURATON}} --no-restore

      - name: Run tests
        run: dotnet test ${{env.SOLUTION}} --no-build --configuration ${{env.BUILD_CONFIGURATON}}
